version: '3'
services:
  web:
    container_name: "sqli-labs"
    build: .
    depends_on:
      - db
    expose:
      - "80"
    links:
      - db
    volumes:
      - ./:/var/www/html
    ports:
      - "7080:80"
  db:
    container_name: "sqli-labs-db"
    image: mysql:5.7
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
